apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: data-requests
  labels:
    strimzi.io/cluster: my-cluster
  namespace: kafka
spec:
  partitions: 1
  replicas: 1
  topicName: data_requests
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: data-responses
  labels:
    strimzi.io/cluster: my-cluster
  namespace: kafka
spec:
  partitions: 1
  replicas: 1
  topicName: data_responses
