replicaCount: 1


image:
  repository: majidni/tracing-demo-app
  pullPolicy: IfNotPresent
  tag: "0e3fa54f67fa2ba430d4bbcc343d01f56d7de0e9"

registry:
  host: "docker.io"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  host: app.majtest.uk
  path: /
  pathType: ImplementationSpecific
  tls:
    enabled: true
    secret: ""

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

tracing:
  enabled: "true"
  otlpEndpoint: "otel-collector-collector.tracing.svc.cluster.local:4317"

apiGateway:
  replicaCount: 1

dataProcessor:
  replicaCount: 1

kafka:
  broker: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"

redis:
  host: "my-redis-master.redis.svc.cluster.local"
  port: 6379
  password: "Test@Redis"

mongodb:
  user: "testapp"
  db: "testapp"
  host: "mongodb-arm.mongodb.svc.cluster.local"
  port: "27017"
  password: "testapp"
